name: Xcode - Test macOS Builds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Xcode Tests
    strategy:
      matrix:
        xcode: ["16.0"]
        macos: ["macos-15"]
    runs-on: ${{ matrix.macos }}
    # runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
          # xcode-version: latest-stable

      - name: Install Dependencies
        run: |
          gem install xcpretty
          # Add other dependencies if needed

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project macOS/Patal.xcodeproj \
            -scheme Patal \
            -destination 'platform=macOS' \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
